# .github/workflows/biweekly-tech-trends.yml
name: "Bi‑Weekly Org Tech Trends"

# Prevent overlap if a previous run is still in flight
concurrency:
  group: tech-trends-post
  cancel-in-progress: true

# Run on schedule + allow manual trigger
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 1,15 * *'  # 09:00 UTC on the 1st & 15th

# Token scopes for this job
permissions:
  contents: read           # needed by checkout
  discussions: write       # to create GitHub Discussions

jobs:
  post-tech-trends:
    runs-on: ubuntu-latest

    # Expose all required env vars in one place
    env:
      # GitHub repo slug
      GITHUB_REPOSITORY:      ${{ github.repository }}

      # OpenAI
      OPENAI_API_KEY:         ${{ secrets.OPENAI_API_KEY }}

      # GitHub App credentials
      GITHUB_APP_ID:          ${{ secrets.SH_APP_ID }}
      GITHUB_INSTALLATION_ID: ${{ secrets.SH_INSTALLATION_ID }}
      APP_PRIVATE_KEY:        ${{ secrets.SH_PRIVATE_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'  # built-in caching

      - name: Explicitly cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: (Optional) Lint & type-check
        run: |
          npm run lint
          npm run type-check

      - name: Generate & post Tech Trends discussion
        run: node scripts/generateTrendDiscussion.js

      - name: Success notification
        if: ${{ success() }}
        run: echo "✅ Tech Trends discussion posted successfully."

      - name: Failure notification
        if: ${{ failure() }}
        run: echo "::error ::❌ Discussion post failed — see logs above."

