name: "Bi‑Weekly Org Tech Trends"

concurrency:
  group: tech-trends-post
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 1,15 * *'  # 09:00 UTC on the 1st & 15th

permissions:
  contents: read
  discussions: write

jobs:
  post-tech-trends:
    runs-on: ubuntu-latest

    defaults:
      run:
        # make sure every `run:` is invoked from the repo root
        working-directory: ${{ github.workspace }}

    env:
      GITHUB_REPOSITORY:      ${{ github.repository }}
      OPENAI_API_KEY:         ${{ secrets.OPENAI_API_KEY }}
      GITHUB_APP_ID:          ${{ secrets.SH_APP_ID }}
      GITHUB_INSTALLATION_ID: ${{ secrets.SH_INSTALLATION_ID }}
      APP_PRIVATE_KEY:        ${{ secrets.SH_PRIVATE_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: (Optional) Lint & type‑check
        run: |
          npm run lint
          npm run type-check

      - name: Generate & post Tech Trends discussion
        run: node scripts/generateTrendDiscussion.js

      - name: Success notification
        if: ${{ success() }}
        run: echo "✅ Tech Trends discussion posted successfully."

      - name: Failure notification
        if: ${{ failure() }}
        run: echo "::error ::❌ Discussion post failed — see logs above."
