name: "Bi‑Weekly Org Tech Trends"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 1,15 * *" # 09:00 UTC on the 1st & 15th

permissions:
  contents: read # for checkout
  discussions: write # to list categories + create discussions

env:
  GITHUB_REPOSITORY: ${{ github.repository }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }} # optional override
  # (no more GitHub App secrets needed when using GITHUB_TOKEN)

jobs:
  post-tech-trends:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Generate & post Tech Trends discussion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # expose built‑in token
        run: node scripts/generateTrendDiscussion.js

      - name: Success notification
        if: ${{ success() }}
        run: echo "✅ Tech Trends discussion posted."

      - name: Failure notification
        if: ${{ failure() }}
        run: echo "::error ::❌ Failed to post Tech Trends discussion."
