name: "Bi‑Weekly Org Tech Trends"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 1,15 * *" # 09:00 UTC on the 1st & 15th

permissions:
  contents: read
  discussions: write

env:
  # OpenAI
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }} # optional override (defaults to "gpt-4")

  # GitHub App ▶︎ these are your secrets named in the repo settings
  GITHUB_APP_ID: ${{ secrets.SH_APP_ID }}
  GITHUB_INSTALLATION_ID: ${{ secrets.SH_INSTALLATION_ID }}
  APP_PRIVATE_KEY: ${{ secrets.SH_PRIVATE_KEY }}

jobs:
  post-tech-trends:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate & post Tech Trends discussion
        # At this point, process.env.GITHUB_APP_ID, .GITHUB_INSTALLATION_ID
        # and .APP_PRIVATE_KEY are all defined for the script.
        run: node scripts/generateTrendDiscussion.js

      - name: Success
        if: ${{ success() }}
        run: echo "✅ Discussion posted by GitHub App."

      - name: Failure
        if: ${{ failure() }}
        run: echo "::error ::❌ Discussion failed — check the logs."
